Set trap only after option parsing (#22)
If we set the cleanup function for every exit, even a simple
"toolbox -h" will run the cleanup function. But since there is nothing
to cleanup, this will lead to a wrong error exit code.

diff --git a/toolbox b/toolbox
--- a/toolbox
+++ b/toolbox
@@ -16,8 +16,6 @@
 
 set -eo pipefail
 
-trap cleanup EXIT
-
 # Defaults
 REGISTRY=registry.opensuse.org
 IMAGE=opensuse/toolbox
@@ -336,6 +334,10 @@ main() {
                 ;;
         esac
     done
+
+    # Don't call trap before, else we will cleanup stuff
+    # where nothing is to cleanup and report wrong error
+    trap cleanup EXIT
 
     # Let's rebuild the image URI (this means that command
     # line, if present, overrides config file)
