Check sub{u,g}id if rootless, and fail early if they're not setup
Don't even start pulling an image, if rootless mode is wanted, but
subuid and subgid are not setup properly for the user.

Instead, print an (hopefully) meaningful error message, with a clear
indication for the user on how to fix the problem.

Deals with issue #18.

Signed-off-by: Dario Faggioli <dfaggioli@suse.com>

diff --git a/toolbox b/toolbox
--- a/toolbox
+++ b/toolbox
@@ -148,6 +148,17 @@ image_runlabel() {
 }
 
 image_pull() {
+    if [ -z ${SUDO} ]; then
+        if [ ! `grep $USER /etc/subuid` ] || [ ! `grep $USER /etc/subgid` ]; then
+            echo "$0: ERROR: rootless mode wanted but no subuid and/or subgid for user '$USER'"
+            echo " Toolbox will only work for this user if rootless podman is configured properly."
+            echo " consider doing something like this:"
+            echo "    sudo usermod --add-subuids 100000-165535 --add-subgids 100000-165535 $USER"
+            echo " and then restart."
+            echo " Or use '-r', for using a rootfull container."
+            exit 1
+        fi
+    fi
     ${SUDO} podman pull "$TOOLBOX_IMAGE"
 }
 
