Support passing just the name of the container to create and enter command
Currently, for specifying the container name, '-c <name>' must be used
(or we can add a tag to the default name with '-t <tag>'). It is however
much more convenient if, at least for the create and enter command
(i.e., only for user toolboxes!), we can just pass the name as an
argument, without the need of any option. E.g.:

  toolbox create work

Or:

  toolbox enter dev

Of course, using either '-c' or '-t' continues to be supported (although,
all these mechanisms are mutually exclusive, and only one must be used).

This is one more step toward CLI compatibility with
gh#containers/toolbox (and, to some extent, with distrobox too).

Signed-off-by: Dario Faggioli <dfaggioli@suse.com>

diff --git a/toolbox b/toolbox
--- a/toolbox
+++ b/toolbox
@@ -216,7 +216,7 @@ container_exec() {
 }
 
 show_help() {
-    echo "USAGE: toolbox [[-h/--help] | [command] [-r/--root] [-u/--user] [-n/--nostop]
+    echo "USAGE: toolbox [[-h/--help] | [list|create [<name>]|enter [<name>]|run] [-r/--root] [-u/--user] [-n/--nostop]
         [-S/--sandbox] [-P/--no-pull] [[-R/--reg <registry>] [-I/--img <image>]|[-i/--image <image_URI>]]
         [[-t/--tag <tag>]|[-c/--container <name>]] [command_to_run]]
 toolbox is a small script that launches a container to let you bring in your favorite debugging or admin tools.
@@ -228,6 +228,11 @@ Commands are optional and imply user mode (-u):
  create: Just create the toolbox
  enter: Enter inside a toolbox (if it does not exist, it is created)
  run: Run command_to_run inside a toolbox (if it does not exist, it is created)
+
+For the create and enter commands, the toolbox name can be specified either:
+ - with -t/--tag, e.g.: 'toolbox enter -t dev'. For user foo, will enter 'toolbox-foo-user-dev'. Or,
+ - with -c/--container, e.g.: 'toolbox create -c work'. Will create 'work'. Or
+ - with just the name of the container, e.g.: 'toolbox enter test'. Will enter 'test'.
 
 Options:
   -h/--help: Shows this help message
@@ -404,12 +409,29 @@ main() {
 
     case $COMMAND in
         create|enter|run)
+            if [ "$COMMAND" = "enter" ] || [ "$COMMAND" = "create" ]; then
+                # enter and create supports the name of the container being
+                # as an argument, so use if it's there. But there must be no
+                # conflict between that and the -c and -t options.
+                if [ $# -ge 1 ]; then
+                    if [ -n "$CHANGE_NAME" ] || [ -n "$TAG" ]; then
+                        echo "ERROR: Cannot determine which container to use between $TOOLBOX_NAME and $1"
+                        show_help
+                        exit 1
+                    fi
+                    TOOLBOX_NAME=$1
+                    shift
+                fi
+            fi
+
             # Cleanup is only needed if we're really starting the container
             trap cleanup EXIT
 
-            if [ "$COMMAND" == "create" ]; then
+            if [ "$COMMAND" = "create" ]; then
+                [ $# -gt 0 ] && echo "WARNING: ignoring the following arguments: $@"
                 create
-            elif [ -z "$*" ]; then
+            elif [ "$COMMAND" = "enter" ] || [ $# -eq 0 ]; then
+                [ "$COMMAND" = "enter" ] && [ $# -gt 0 ] && echo "WARNING: ignoring the following arguments: $@"
                 run ${TOOLBOX_SHELL}
             else
                 run "$@"
